server:
  servlet:
      contextPath: /api
  logging:
    enabled: false
  port: 8080

spring:
  cloud:
    refresh:
      enabled: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:h2:mem:testdb

elide:
  json-api:
    path: /api/v1
    enabled: true
  graphql:
    path: /graphql/api/v1
    enabled: true
  api-docs:
    path: /doc
    enabled: true
    version: openapi_3_0